code --install-extension vscodevim.vim
code --install-extension eamodio.gitlens
code --install-extension pkief.material-icon-theme
code --install-extension auchenberg.vscode-browser-preview
code --install-extension bungcip.better-toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension dendron.dendron
code --install-extension dendron.dendron-markdown-preview-enhanced
code --install-extension dendron.dendron-paste-image
code --install-extension dendron.dendron-snippet-maker
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GraphQL.vscode-graphql
code --install-extension hashicorp.terraform
code --install-extension JuanBlanco.solidity
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension pflannery.vscode-versionlens
code --install-extension Prisma.prisma
code --install-extension redwoodjs.redwood
code --install-extension unpublished.sourcekit-lsp
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost

ln -sf $HOME/.dotfiles/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
